addons:
  chrome: stable
env:
  - BROWSER_PATH=/usr/bin/google-chrome
gemfile:
  - gemfiles/capybara2.gemfile
  - gemfiles/websocketdriver6.gemfile
  - gemfiles/latest.gemfile
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
