addons:
  chrome: stable
gemfile:
  - gemfiles/capybara-2.x.gemfile
  - gemfiles/capybara-3.x.gemfile
  - gemfiles/websocket-driver-6.x.gemfile
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/websocket-driver-6.x.gemfile
  - rvm: 2.4
    gemfile: gemfiles/websocket-driver-6.x.gemfile
  - rvm: 2.6
    gemfile: gemfiles/websocket-driver-6.x.gemfile
